#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
#ifndef ACUANTDOCUMENTPROCESSING_SWIFT_H
#define ACUANTDOCUMENTPROCESSING_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AcuantCommon;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AcuantDocumentProcessing",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC24AcuantDocumentProcessing7Address")
@interface Address : NSObject
@end

typedef SWIFT_ENUM(NSInteger, AuthenticationResult, open) {
  AuthenticationResultUnknown = 0,
  AuthenticationResultPassed = 1,
  AuthenticationResultFailed = 2,
  AuthenticationResultSkipped = 3,
  AuthenticationResultCaution = 4,
  AuthenticationResultAttention = 5,
};

typedef SWIFT_ENUM(NSInteger, AuthenticationSensitivity, open) {
  AuthenticationSensitivityNormal = 0,
  AuthenticationSensitivityHigh = 1,
  AuthenticationSensitivityLow = 2,
};

@class NSString;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing10Biographic")
@interface Biographic : NSObject
@property (nonatomic, readonly) NSInteger age;
@property (nonatomic, readonly, copy) NSString * _Nullable birthDate;
@property (nonatomic, readonly, copy) NSString * _Nullable expirationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable fullName;
@property (nonatomic, readonly) NSInteger unparsedGender;
@property (nonatomic, copy) NSString * _Nullable photo;
@end

@class ClassificationDetails;
@class DocumentType;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing14Classification")
@interface Classification : NSObject
@property (nonatomic, readonly) NSInteger unparsedMode;
@property (nonatomic, readonly) BOOL orientationChanged;
@property (nonatomic, readonly) BOOL presentationChanged;
@property (nonatomic, readonly, strong) ClassificationDetails * _Nullable classificationDetails;
@property (nonatomic, readonly, strong) DocumentType * _Nullable type;
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing21ClassificationDetails")
@interface ClassificationDetails : NSObject
@property (nonatomic, readonly, strong) DocumentType * _Nullable front;
@property (nonatomic, readonly, strong) DocumentType * _Nullable back;
@end

typedef SWIFT_ENUM(NSInteger, ClassificationMode, open) {
  ClassificationModeAutomatic = 0,
  ClassificationModeManual = 1,
};

@class AcuantError;

SWIFT_PROTOCOL("_TtP24AcuantDocumentProcessing22CreateInstanceDelegate_")
@protocol CreateInstanceDelegate
- (void)instanceCreatedWithInstanceId:(NSString * _Nullable)instanceId error:(AcuantError * _Nullable)error;
@end


SWIFT_PROTOCOL("_TtP24AcuantDocumentProcessing14DeleteDelegate_")
@protocol DeleteDelegate
- (void)instanceDeletedWithSuccess:(BOOL)success;
@end

@class DeviceType;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing10DeviceInfo")
@interface DeviceInfo : NSObject
@property (nonatomic, readonly) BOOL hasContactlessChipReader;
@property (nonatomic, readonly) BOOL hasMagneticStripeReader;
@property (nonatomic, readonly, copy) NSString * _Nullable serialNumber;
@property (nonatomic, readonly, strong) DeviceType * _Nullable type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing10DeviceType")
@interface DeviceType : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable manufacturer;
@property (nonatomic, readonly, copy) NSString * _Nullable model;
@property (nonatomic, readonly) NSInteger unparsedSensorType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing13DocumentAlert")
@interface DocumentAlert : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nullable actions;
@property (nonatomic, readonly, copy) NSString * _Nullable actionDescription;
@property (nonatomic, readonly, copy) NSString * _Nullable disposition;
@property (nonatomic, readonly, copy) NSString * _Nullable information;
@property (nonatomic, readonly, copy) NSString * _Nullable key;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly) NSInteger unparsedResult;
@property (nonatomic, readonly, copy) NSString * _Nullable model;
@end

typedef SWIFT_ENUM(NSInteger, DocumentClass, open) {
  DocumentClassUnknown = 0,
  DocumentClassPassport = 1,
  DocumentClassVisa = 2,
  DocumentClassDriversLicense = 3,
  DocumentClassIdentificationCard = 4,
  DocumentClassPermit = 5,
  DocumentClassCurrency = 6,
  DocumentClassResidenceDocument = 7,
  DocumentClassTravelDocument = 8,
  DocumentClassBirthCertificate = 9,
  DocumentClassVehicleRegistration = 10,
  DocumentClassOther = 11,
  DocumentClassWeaponLicense = 12,
  DocumentClassTribalIdentification = 13,
  DocumentClassVoterIdentification = 14,
  DocumentClassMilitary = 15,
  DocumentClassConsularIdentification = 16,
};


SWIFT_PROTOCOL("_TtP24AcuantDocumentProcessing30DocumentClassificationDelegate_")
@protocol DocumentClassificationDelegate
- (void)documentClassifiedWithSuccess:(BOOL)success classification:(Classification * _Nullable)classification error:(AcuantError * _Nullable)error;
@end

@class Rectangle;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing17DocumentDataField")
@interface DocumentDataField : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly) NSInteger dataSource;
@property (nonatomic, readonly, copy) NSString * _Nullable fieldDescrption;
@property (nonatomic, readonly) BOOL isImage;
@property (nonatomic, readonly, copy) NSString * _Nullable key;
@property (nonatomic, readonly, strong) Rectangle * _Nullable regionOfInterest;
@property (nonatomic, readonly, copy) NSString * _Nullable regionReference;
@property (nonatomic, readonly) double reliability;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@end

typedef SWIFT_ENUM(NSInteger, DocumentDataSource, open) {
  DocumentDataSourceNone = 0,
  DocumentDataSourceBarcode1D = 1,
  DocumentDataSourceBarcode2D = 2,
  DocumentDataSourceContactlessChip = 3,
  DocumentDataSourceMachineReadableZone = 4,
  DocumentDataSourceMagneticStripe = 5,
  DocumentDataSourceVisualInspectionZone = 6,
  DocumentDataSourceOther = 7,
};

typedef SWIFT_ENUM(NSInteger, DocumentDataType, open) {
  DocumentDataTypeBarcode2D = 0,
  DocumentDataTypeMachineReadableZone = 1,
  DocumentDataTypeMagneticStripe = 2,
};

typedef SWIFT_ENUM(NSInteger, DocumentElement, open) {
  DocumentElementUnknown = 0,
  DocumentElementNone = 1,
  DocumentElementPhoto = 2,
  DocumentElementData = 3,
  DocumentElementSubstrate = 4,
  DocumentElementOverlay = 5,
};


SWIFT_CLASS("_TtC24AcuantDocumentProcessing13DocumentField")
@interface DocumentField : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger unparsedDataSource;
@property (nonatomic, readonly, copy) NSString * _Nullable fieldDescription;
@property (nonatomic, readonly) BOOL isImage;
@property (nonatomic, readonly, copy) NSString * _Nullable key;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable regionReference;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@property (nonatomic, readonly, copy) NSString * _Nullable value;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable dataFieldReference;
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing13DocumentImage")
@interface DocumentImage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger horizontalResolution;
@property (nonatomic, readonly) NSInteger verticalResolution;
@property (nonatomic, readonly) NSInteger unparsedSide;
@property (nonatomic, readonly) NSInteger unparsedLight;
@property (nonatomic, readonly) BOOL isCropped;
@property (nonatomic, readonly) BOOL isTampered;
@property (nonatomic, readonly, copy) NSString * _Nullable mimeType;
@property (nonatomic, readonly, copy) NSString * _Nullable uri;
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing17DocumentImageType")
@interface DocumentImageType : NSObject
@property (nonatomic, readonly) NSInteger unparsedLight;
@property (nonatomic, readonly) NSInteger unparsedSide;
@end

typedef SWIFT_ENUM(NSInteger, DocumentProcessMode, open) {
  DocumentProcessModeDefault = 0,
  DocumentProcessModeCaptureData = 1,
  DocumentProcessModeAuthenticate = 2,
  DocumentProcessModeBarcode = 3,
};

@class IdOptions;
@class IdData;
@protocol UploadImageDelegate;
@protocol GetDataDelegate;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing18DocumentProcessing")
@interface DocumentProcessing : NSObject
+ (void)createInstanceWithOptions:(IdOptions * _Nonnull)options delegate:(id <CreateInstanceDelegate> _Nonnull)delegate;
+ (void)uploadImageWithInstancdId:(NSString * _Nonnull)instancdId data:(IdData * _Nonnull)data options:(IdOptions * _Nonnull)options delegate:(id <UploadImageDelegate> _Nonnull)delegate;
+ (void)uploadBarcodeWithInstanceId:(NSString * _Nonnull)instanceId barcodeString:(NSString * _Nonnull)barcodeString delegate:(id <UploadImageDelegate> _Nonnull)delegate;
+ (void)getDataWithInstanceId:(NSString * _Nonnull)instanceId isHealthCard:(BOOL)isHealthCard delegate:(id <GetDataDelegate> _Nonnull)delegate;
+ (void)deleteInstanceWithInstanceId:(NSString * _Nonnull)instanceId type:(enum DeleteType)type delegate:(id <DeleteDelegate> _Nonnull)delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing14DocumentRegion")
@interface DocumentRegion : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly) NSInteger unparsedDocumentElement;
@property (nonatomic, readonly, copy) NSString * _Nonnull imageReference;
@property (nonatomic, readonly, copy) NSString * _Nullable key;
@property (nonatomic, readonly, strong) Rectangle * _Nullable rectangle;
@end

typedef SWIFT_ENUM(NSInteger, DocumentSide, open) {
  DocumentSideFront = 0,
  DocumentSideBack = 1,
};

typedef SWIFT_ENUM(NSInteger, DocumentSize, open) {
  DocumentSizeUnknown = 0,
  DocumentSizeId1 = 1,
  DocumentSizeId2 = 2,
  DocumentSizeId3 = 3,
  DocumentSizeLetter = 4,
  DocumentSizeCheckCurrency = 5,
  DocumentSizeCustom = 6,
};


SWIFT_CLASS("_TtC24AcuantDocumentProcessing12DocumentType")
@interface DocumentType : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger unparsedDocumentClass;
@property (nonatomic, readonly, copy) NSString * _Nullable classCode;
@property (nonatomic, readonly, copy) NSString * _Nullable className;
@property (nonatomic, readonly, copy) NSString * _Nullable countryCode;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable geographicRegions;
@property (nonatomic, readonly) BOOL isGeneric;
@property (nonatomic, readonly, copy) NSString * _Nullable issue;
@property (nonatomic, readonly, copy) NSString * _Nullable issueType;
@property (nonatomic, readonly, copy) NSString * _Nullable issuerCode;
@property (nonatomic, readonly, copy) NSString * _Nullable issuerName;
@property (nonatomic, readonly) NSInteger unparsedIssuerType;
@property (nonatomic, readonly, copy) NSString * _Nullable keesingCode;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly) NSInteger unparsedSize;
@property (nonatomic, readonly, copy) NSArray<DocumentImageType *> * _Nonnull supportedImages;
@end

typedef SWIFT_ENUM(NSInteger, GenderType, open) {
  GenderTypeUnspecified = 0,
  GenderTypeMale = 1,
  GenderTypeFemale = 2,
  GenderTypeUnknown = 3,
};

@class ProcessingResult;

SWIFT_PROTOCOL("_TtP24AcuantDocumentProcessing15GetDataDelegate_")
@protocol GetDataDelegate
- (void)processingResultReceivedWithProcessingResult:(ProcessingResult * _Nonnull)processingResult;
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing16ProcessingResult")
@interface ProcessingResult : NSObject
@property (nonatomic, strong) AcuantError * _Nullable error;
+ (ProcessingResult * _Nonnull)createInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing25HealthInsuranceCardResult")
@interface HealthInsuranceCardResult : ProcessingResult
@property (nonatomic, readonly, copy) NSString * _Nullable copayEr;
@property (nonatomic, readonly, copy) NSString * _Nullable copayOv;
@property (nonatomic, readonly, copy) NSString * _Nullable copaySp;
@property (nonatomic, readonly, copy) NSString * _Nullable copayUc;
@property (nonatomic, readonly, copy) NSString * _Nullable coverage;
@property (nonatomic, readonly, copy) NSString * _Nullable contractCode;
@property (nonatomic, readonly, copy) NSString * _Nullable dateOfBirth;
@property (nonatomic, readonly, copy) NSString * _Nullable deductible;
@property (nonatomic, readonly, copy) NSString * _Nullable effectiveDate;
@property (nonatomic, readonly, copy) NSString * _Nullable employer;
@property (nonatomic, readonly, copy) NSString * _Nullable expirationDate;
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
@property (nonatomic, readonly, copy) NSString * _Nullable groupName;
@property (nonatomic, readonly, copy) NSString * _Nullable groupNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable issuerNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
@property (nonatomic, readonly, copy) NSString * _Nullable memberId;
@property (nonatomic, readonly, copy) NSString * _Nullable memberName;
@property (nonatomic, readonly, copy) NSString * _Nullable middleName;
@property (nonatomic, readonly, copy) NSString * _Nullable namePrefix;
@property (nonatomic, readonly, copy) NSString * _Nullable nameSuffix;
@property (nonatomic, readonly, copy) NSString * _Nullable other;
@property (nonatomic, readonly, copy) NSString * _Nullable payerId;
@property (nonatomic, readonly, copy) NSString * _Nullable planAdmin;
@property (nonatomic, readonly, copy) NSString * _Nullable planProvider;
@property (nonatomic, readonly, copy) NSString * _Nullable planType;
@property (nonatomic, readonly, copy) NSString * _Nullable rxBin;
@property (nonatomic, readonly, copy) NSString * _Nullable rxGroup;
@property (nonatomic, readonly, copy) NSString * _Nullable rxId;
@property (nonatomic, readonly, copy) NSString * _Nullable rxPcn;
@property (nonatomic, readonly, copy) NSArray<Address *> * _Nullable addresses;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable planCodes;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable telephones;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable emails;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable webs;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionId;
@property (nonatomic, copy) NSString * _Nullable instanceID;
@property (nonatomic, readonly, strong) UIImage * _Nullable frontImage;
@property (nonatomic, readonly, strong) UIImage * _Nullable backImage;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Subscription;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing8IDResult")
@interface IDResult : ProcessingResult
@property (nonatomic, readonly, copy) NSString * _Nonnull instanceID;
@property (nonatomic, readonly) NSInteger unparsedAuthenticationSensitivity;
@property (nonatomic, readonly, copy) NSString * _Nullable engineVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable libraryVersion;
@property (nonatomic, readonly) NSInteger unparsedProcessMode;
@property (nonatomic) NSInteger unparsedResult;
@property (nonatomic, readonly, strong) Subscription * _Nullable subscription;
@property (nonatomic, readonly, strong) Biographic * _Nullable biographic;
@property (nonatomic, readonly, strong) Classification * _Nullable classification;
@property (nonatomic, readonly, strong) DeviceInfo * _Nullable device;
@property (nonatomic, readonly, copy) NSArray<DocumentAlert *> * _Nullable alerts;
@property (nonatomic, readonly, copy) NSArray<DocumentDataField *> * _Nullable dataFields;
@property (nonatomic, readonly, copy) NSArray<DocumentField *> * _Nullable fields;
@property (nonatomic, readonly, copy) NSArray<DocumentImage *> * _Nullable images;
@property (nonatomic, readonly, copy) NSArray<DocumentRegion *> * _Nullable regions;
@property (nonatomic, readonly) NSInteger unparsedTamperResult;
@property (nonatomic, readonly) NSInteger unparsedTamperSensitivity;
@end


SWIFT_CLASS("_TtC24AcuantDocumentProcessing6IdData")
@interface IdData : NSObject
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable barcodeString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (IdData * _Nonnull)createInstance SWIFT_WARN_UNUSED_RESULT;
@end

enum TamperSensitivity : NSInteger;

SWIFT_CLASS("_TtC24AcuantDocumentProcessing9IdOptions")
@interface IdOptions : NSObject
@property (nonatomic) enum DocumentSide cardSide;
@property (nonatomic) BOOL isHealthCard;
@property (nonatomic) BOOL isRetrying;
@property (nonatomic) enum AuthenticationSensitivity authenticationSensitivity;
@property (nonatomic) enum TamperSensitivity tamperSensitivity;
@property (nonatomic, copy) NSString * _Nullable countryCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (IdOptions * _Nonnull)createInstance SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, IssuerType, open) {
  IssuerTypeUnknown = 0,
  IssuerTypeCountry = 1,
  IssuerTypeStateProvince = 2,
  IssuerTypeTribal = 3,
  IssuerTypeMunicipality = 4,
  IssuerTypeBusiness = 5,
  IssuerTypeOther = 6,
};

typedef SWIFT_ENUM(NSInteger, LightSource, open) {
  LightSourceWhite = 0,
  LightSourceNearInfrared = 1,
  LightSourceUltravioletA = 2,
  LightSourceCoaxialWhite = 3,
  LightSourceCoaxialNearInfrared = 4,
};



SWIFT_CLASS("_TtC24AcuantDocumentProcessing9Rectangle")
@interface Rectangle : NSObject
@property (nonatomic, readonly) NSInteger height;
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger x;
@property (nonatomic, readonly) NSInteger y;
@end

typedef SWIFT_ENUM(NSInteger, SensorType, open) {
  SensorTypeUnknown = 0,
  SensorTypeCamera = 1,
  SensorTypeScanner = 2,
  SensorTypeMobile = 3,
};


SWIFT_CLASS("_TtC24AcuantDocumentProcessing12Subscription")
@interface Subscription : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly) NSInteger unparsedDocumentProcessMode;
@property (nonatomic, readonly) BOOL isActive;
@property (nonatomic, readonly) BOOL isDevelopment;
@property (nonatomic, readonly) BOOL isTrial;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly) BOOL storePII;
@end

typedef SWIFT_ENUM(NSInteger, TamperSensitivity, open) {
  TamperSensitivityNormal = 0,
  TamperSensitivityHigh = 1,
  TamperSensitivityLow = 2,
};


SWIFT_PROTOCOL("_TtP24AcuantDocumentProcessing19UploadImageDelegate_")
@protocol UploadImageDelegate
- (void)imageUploadedWithError:(AcuantError * _Nullable)error classification:(Classification * _Nullable)classification;
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
