---
kind: pipeline
type: kubernetes
name: Linux ARM64

platform:
  arch: arm64

steps:
- name: test
  image: docker-registry.dev:5000/tesseract:latest
  commands:
  - swift test

trigger:
  paths:
    include:
    - "**.swift"
    - "**.modulemap"
    - ".drone.yml"
  event:
  - pull_request
  - push
  - tag

---
kind: pipeline
type: kubernetes
name: build-image

platform:
  arch: arm64

steps:
- name: docker_publish_dry_run
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: docker/drone.Dockerfile
    registry: docker-registry.dev:5000
    repo: docker-registry.dev:5000/tesseract
    insecure: true

- name: docker_publish
  image: plugins/docker
  settings:
    dockerfile: docker/drone.Dockerfile
    registry: docker-registry.dev:5000
    repo: docker-registry.dev:5000/tesseract
    insecure: true
  when:
    event:
    - tag

trigger:
  paths:
    include:
    - docker/drone.Dockerfile
---
kind: pipeline
type: exec
name: macOS M1 Tests

platform:
  os: darwin
  arch: arm64

steps:
- name: Test Swift Package
  commands:
  - xcode 12.5.b3 swift test

- name: Test Native macOS
  commands:
  - |
    xcode 12.5.b3 xcodebuild \
    -scheme SwiftyTesseract \
    -destination 'platform=macOS,arch=arm64' \
    test

- name: Test Rosetta macOS
  commands:
  - |
    xcode 12.5.b3 xcodebuild \
    -scheme SwiftyTesseract \
    -destination 'platform=macOS,arch=x86_64' \
    test

# Native Catalyst is unable to execute tests: FB9031309
- name: Test Rosetta Catalyst
  commands:
  - |
    xcode 12.5.b3 xcodebuild \
    -scheme SwiftyTesseract \
    -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' \
    test

- name: Test iOS
  commands:
  - |
    xcode 12.5.b3 xcodebuild \
    -scheme SwiftyTesseract \
    -destination 'platform=iOS Simulator,name=iPhone 11' \
    test

- name: Test Example - CLI
  commands:
  - |
    cd Examples/cli
    xcode 12.5.b3 swift test

- name: Test Example - Vapor
  commands:
  - |
    cd Examples/VaporExample
    xcode 12.5.b3 swift test

trigger:
  paths:
    include:
    - "**.swift"
    - "**.modulemap"
    - ".drone.yml"
  event:
  - pull_request
  - push
  - tag
